//
//  SkeletonJointName.swift
//  try-reality-kit
//
//  Created by fuziki on 2022/08/12
//
//

import Foundation

public enum SkeletonJoint: String, CaseIterable {
    case root = "root"
    case hips = "hips_joint"
    case leftUpleg = "left_upLeg_joint"
    case leftLeg = "left_leg_joint"
    case leftFoot = "left_foot_joint"
    case leftToes = "left_toes_joint"
    case leftToesend = "left_toesEnd_joint"
    case rightUpleg = "right_upLeg_joint"
    case rightLeg = "right_leg_joint"
    case rightFoot = "right_foot_joint"
    case rightToes = "right_toes_joint"
    case rightToesend = "right_toesEnd_joint"
    case spine1 = "spine_1_joint"
    case spine2 = "spine_2_joint"
    case spine3 = "spine_3_joint"
    case spine4 = "spine_4_joint"
    case spine5 = "spine_5_joint"
    case spine6 = "spine_6_joint"
    case spine7 = "spine_7_joint"
    case neck1 = "neck_1_joint"
    case neck2 = "neck_2_joint"
    case neck3 = "neck_3_joint"
    case neck4 = "neck_4_joint"
    case head = "head_joint"
    case jaw = "jaw_joint"
    case chin = "chin_joint"
    case nose = "nose_joint"
    case rightEye = "right_eye_joint"
    case rightEyeupperlid = "right_eyeUpperLid_joint"
    case rightEyelowerlid = "right_eyeLowerLid_joint"
    case rightEyeball = "right_eyeball_joint"
    case leftEye = "left_eye_joint"
    case leftEyeupperlid = "left_eyeUpperLid_joint"
    case leftEyelowerlid = "left_eyeLowerLid_joint"
    case leftEyeball = "left_eyeball_joint"
    case rightShoulder1 = "right_shoulder_1_joint"
    case rightArm = "right_arm_joint"
    case rightForearm = "right_forearm_joint"
    case rightHand = "right_hand_joint"
    case rightHandpinkystart = "right_handPinkyStart_joint"
    case rightHandpinky1 = "right_handPinky_1_joint"
    case rightHandpinky2 = "right_handPinky_2_joint"
    case rightHandpinky3 = "right_handPinky_3_joint"
    case rightHandpinkyend = "right_handPinkyEnd_joint"
    case rightHandringstart = "right_handRingStart_joint"
    case rightHandring1 = "right_handRing_1_joint"
    case rightHandring2 = "right_handRing_2_joint"
    case rightHandring3 = "right_handRing_3_joint"
    case rightHandringend = "right_handRingEnd_joint"
    case rightHandmidstart = "right_handMidStart_joint"
    case rightHandmid1 = "right_handMid_1_joint"
    case rightHandmid2 = "right_handMid_2_joint"
    case rightHandmid3 = "right_handMid_3_joint"
    case rightHandmidend = "right_handMidEnd_joint"
    case rightHandindexstart = "right_handIndexStart_joint"
    case rightHandindex1 = "right_handIndex_1_joint"
    case rightHandindex2 = "right_handIndex_2_joint"
    case rightHandindex3 = "right_handIndex_3_joint"
    case rightHandindexend = "right_handIndexEnd_joint"
    case rightHandthumbstart = "right_handThumbStart_joint"
    case rightHandthumb1 = "right_handThumb_1_joint"
    case rightHandthumb2 = "right_handThumb_2_joint"
    case rightHandthumbend = "right_handThumbEnd_joint"
    case leftShoulder1 = "left_shoulder_1_joint"
    case leftArm = "left_arm_joint"
    case leftForearm = "left_forearm_joint"
    case leftHand = "left_hand_joint"
    case leftHandpinkystart = "left_handPinkyStart_joint"
    case leftHandpinky1 = "left_handPinky_1_joint"
    case leftHandpinky2 = "left_handPinky_2_joint"
    case leftHandpinky3 = "left_handPinky_3_joint"
    case leftHandpinkyend = "left_handPinkyEnd_joint"
    case leftHandringstart = "left_handRingStart_joint"
    case leftHandring1 = "left_handRing_1_joint"
    case leftHandring2 = "left_handRing_2_joint"
    case leftHandring3 = "left_handRing_3_joint"
    case leftHandringend = "left_handRingEnd_joint"
    case leftHandmidstart = "left_handMidStart_joint"
    case leftHandmid1 = "left_handMid_1_joint"
    case leftHandmid2 = "left_handMid_2_joint"
    case leftHandmid3 = "left_handMid_3_joint"
    case leftHandmidend = "left_handMidEnd_joint"
    case leftHandindexstart = "left_handIndexStart_joint"
    case leftHandindex1 = "left_handIndex_1_joint"
    case leftHandindex2 = "left_handIndex_2_joint"
    case leftHandindex3 = "left_handIndex_3_joint"
    case leftHandindexend = "left_handIndexEnd_joint"
    case leftHandthumbstart = "left_handThumbStart_joint"
    case leftHandthumb1 = "left_handThumb_1_joint"
    case leftHandthumb2 = "left_handThumb_2_joint"
    case leftHandthumbend = "left_handThumbEnd_joint"
}
